using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TIC.ClientAPI.Models
{
    public class Applicant
    {
        public string Email;
        public string SellerEmail;
        public string SellerName;       // Allied Corporate Name here?  Or sales person?
        public int SortOrder;
        public string FirstName;
        public string MiddleInit;
        public string LastName;
        public int Suffix;
        public DateTime DateOfBirth;
        public string Address;
        public string Address2;
        public int Zip;
        public string City;
        public string State;
        public int Years;
        public string SSN;
        public string Employer;
        public decimal Income;
        public int EmpYears;
//         public int CoApplicantYears;
        public string AddressMailing;
        public string AddressMailing2;
        public int ZipMailing;
        public string CityMailing;
        public string StateMailing;
        public string Phone;
        public string HomeExt;
        public string Cell;
        public string IDNumber;
        public int EmpZip;
        public string EmpCity;
        public string EmpState;
        public string EmpTitle;
        public string EmpPhone;
        public string EmpExt;
        public decimal MortgageAmt;
        public bool Own;
        public decimal Deposit;
        public string BankName;
        public string BankZip;
        public string BankAccountNumber;
        public string BankCity;
        public int BankRoutingNumber;
        public string BankState;
        public string BankPhone;
        public int Qty1;
        public int Qty2;
        public int Qty3;
        public int Qty4;
        public int Qty5;
        public int Qty6;
        public int Qty7;
        public int Qty8;
        public string Item1;
        public string Item2;
        public string Item3;
        public string Item4;
        public string Item5;
        public string Item6;
        public string Item7;
        public string Item8;
        public string Model1;
        public string Model2;
        public string Model3;
        public string Model4;
        public string Model5;
        public string Model6;
        public string Model7;
        public string Model8;
        public decimal SalesPrice;
        public int MDDChosen;
        public bool AutomaticPayment;
        public string SpecialInstructions;
        public float APRRate;
        public string SellerAddress;
        public string SellerCity;
        public string SellerState;
        public int SellerZip;
        // public decimal Balance;
    }
}